import test from 'node:test';
import assert from 'node:assert/strict';
import {readEDF,voltageFactor,sampleRange,envelopeIndices,fitWindow,intervalMetrics,csvRows} from '../edf.mjs';
function fixture({plus=false,discontinuous=false,unknown=false}={}){
  const ns=plus?3:2,counts=plus?[4,2,64]:[4,2],header=256*(ns+1),size=counts.reduce((a,b)=>a+b,0)*2,buffer=new ArrayBuffer(header+size*2),bytes=new Uint8Array(buffer),v=new DataView(buffer);bytes.fill(32,0,header);
  const put=(offset,width,value)=>bytes.set(new TextEncoder().encode(String(value).padEnd(width,' ')),offset);
  put(0,8,0);put(168,8,'07.10.26');put(176,8,'12.00.00');put(184,8,header);put(192,44,plus?(discontinuous?'EDF+D':'EDF+C'):'');put(236,8,unknown?-1:2);put(244,8,1);put(252,4,ns);
  const fields=[[16,['ECG','Slow','EDF Annotations']],[80,['','','']],[8,['uV','mV','']],[8,[-1000,-2,-1]],[8,[1000,2,1]],[8,[-32768,-32768,-32768]],[8,[32767,32767,32767]],[80,['N:50Hz','','']],[8,counts],[32,['','','']]];let offset=256;
  for(const[width,values]of fields){for(let i=0;i<ns;i++)put(offset+i*width,width,values[i]);offset+=ns*width;}
  for(let r=0;r<2;r++){let offset=header+r*size;for(let j=0;j<4;j++)v.setInt16(offset+j*2,[-32768,0,32767,-100][j],true);offset+=8;v.setInt16(offset,-1000,true);v.setInt16(offset+2,1000,true);offset+=4;if(plus){const tal=`+${r}\x14\x14\0+${r+.25}\x150.1\x14test event\x14\0`;bytes.set(new TextEncoder().encode(tal),offset);}}
  return buffer;
}
test('calibrated little-endian samples and mixed rates',()=>{const r=readEDF(fixture());assert.equal(r.channels.length,2);assert.equal(r.channels[0].sampleRate,4);assert.equal(r.channels[1].sampleRate,2);assert.equal(r.channels[0].samples[0],-1000);assert.equal(r.channels[0].samples[2],1000);assert.equal(r.channels[0].samples[1],-1000+32768*2000/65535);assert.equal(r.start,'2026-10-07T12:00:00');assert.equal(r.channels[0].samples.length,8);});
test('EDF+C annotations and unknown record count',()=>{const r=readEDF(fixture({plus:true,unknown:true}));assert.equal(r.annotations.length,2);assert.equal(r.annotations[0].onset_s,.25);assert.equal(r.annotations[0].duration_s,.1);assert.equal(r.annotations[0].description,'test event');assert.equal(r.channels.length,2);assert.equal(r.warnings[0],'Record count inferred from complete data records.');});
test('reject truncated, discontinuous, invalid calibration and BDF',()=>{assert.throws(()=>readEDF(fixture().slice(0,-1)),/truncated/);assert.throws(()=>readEDF(fixture({plus:true,discontinuous:true})),/Discontinuous/);const bad=fixture();new Uint8Array(bad).fill(32,256+2*104,256+2*104+8);assert.throws(()=>readEDF(bad),/numeric/);assert.throws(()=>readEDF(new ArrayBuffer(256)),/supported/);});
test('units, original shifted sample windows and CSV quoting',()=>{assert.equal(voltageFactor('µV','mV'),.001);assert.equal(voltageFactor('mV','µV'),1000);assert.throws(()=>voltageFactor('','mV'));const r=readEDF(fixture()),c=r.channels[0];assert.deepEqual(sampleRange(c,.6,1.1,.1),[2,4]);const rows=[...csvRows([{id:'a',filename:'a,"b.edf',channel:c,offset:.1}],.6,1.1,'mV')];assert.equal(rows.length,3);assert.ok(rows[1].includes('"a,""b.edf"'));assert.ok(rows[1].includes(',0.5,0.6,0.1,1'));});
test('navigation, extrema and equal/reversed ruler points',()=>{assert.deepEqual(fitWindow(9,12,0,10),[7,10]);assert.deepEqual(fitWindow(-3,2,0,10),[0,5]);assert.equal(intervalMetrics(1,2).reciprocal_hz,1);assert.equal(intervalMetrics(2,1).interval_ms,1000);assert.equal(intervalMetrics(1,1).reciprocal_hz,null);assert.throws(()=>intervalMetrics(NaN,2));const values=new Float64Array(10000);values[415]=100;values[887]=-100;const indices=envelopeIndices(values,0,values.length,100);assert.ok(indices.includes(415)&&indices.includes(887));assert.equal(indices[0],0);assert.equal(indices.at(-1),9999);assert.ok(indices.every((x,i)=>i===0||x>indices[i-1]));});
